server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_URL}:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/accounts/(?<path>swagger.*), /$\{path}
            - RewritePath=/accounts/(?<path>v3.*), /$\{path}
        - id: movement-service
          uri: lb://movement-service
          predicates:
            - Path=/movements/**
          filters:
            - RewritePath=/movements/(?<path>swagger.*), /$\{path}
            - RewritePath=/movements/(?<path>v3.*), /$\{path}
  application:
    name: gateway-service