server:
  port: 0 # El puerto 0 indica un puerto aleatorio
  error:
    include-message: always
spring:
  application:
    name: accounts-service # Nombre de la aplicaci칩n
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/${DB} # URL de la base de datos a la que se conectara
    driverClassName: com.mysql.cj.jdbc.Driver # Driver utilizado para el manejo de la base de datos
    username: ${DB_USER} # Nombre de usuario de la base de datos
    password: ${DB_PASS} # Contrase침a de la base de datos
  jpa:
    hibernate:
      ddl-auto: update # Indica que se debe actualizar el esquema de la base de datos al inicializar la aplicaci칩n
  boot:
    admin:
      client:
        url: http://${ADMIN_URL}:8086 # URL del servidor Spring Boot Admin

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n" # Formato de los logs de la aplicaci칩n

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_URL}:8099/eureka/ # URL del servidor Eureka

feign:
  circuitbreaker:
    enabled: true # Activar el circuitbreaker en los clientes feign

management:
  endpoints:
    web:
      exposure:
        include: "*" # Exponer todos los endpoints para el Admin Server